name: GHPages test

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
      - name: Install
        run: pnpm install
      - name: Build
        run: |
          cd packages/eslint-plugin-svelte
          pnpm run update
          pnpm build
          cd ../../docs-svelte-kit
          export NODE_OPTIONS="--max-old-space-size=8192"
          pnpm build
